In [0]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

In [2]:
prior = pd.read_csv("./data/order_products__prior.csv")

In [3]:
products = pd.read_csv("./data/products.csv")

In [4]:
orders = pd.read_csv("./data/orders.csv")

In [5]:
aisles = pd.read_csv("./data/aisles.csv")

In [6]:
# 合并到一张表中
_mg = pd.merge(prior, products, on=['product_id', 'product_id'])

In [7]:
_mg = pd.merge(_mg, orders, on=['order_id', 'order_id'])

In [8]:
mt = pd.merge(_mg, aisles, on=['aisle_id', 'aisle_id'])

In [9]:
mt.head(10)

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,aisle
0,2,33120,1,1,Organic Egg Whites,86,16,202279,prior,3,5,9,8.0,eggs
1,26,33120,5,0,Organic Egg Whites,86,16,153404,prior,2,0,16,7.0,eggs
2,120,33120,13,0,Organic Egg Whites,86,16,23750,prior,11,6,8,10.0,eggs
3,327,33120,5,1,Organic Egg Whites,86,16,58707,prior,21,6,9,8.0,eggs
4,390,33120,28,1,Organic Egg Whites,86,16,166654,prior,48,0,12,9.0,eggs
5,537,33120,2,1,Organic Egg Whites,86,16,180135,prior,15,2,8,3.0,eggs
6,582,33120,7,1,Organic Egg Whites,86,16,193223,prior,6,2,19,10.0,eggs
7,608,33120,5,1,Organic Egg Whites,86,16,91030,prior,11,3,21,12.0,eggs
8,623,33120,1,1,Organic Egg Whites,86,16,37804,prior,63,3,12,3.0,eggs
9,689,33120,4,1,Organic Egg Whites,86,16,108932,prior,16,1,13,3.0,eggs

In [10]:
# 交叉表（特殊分组工具）

In [11]:
cross = pd.crosstab(mt['user_id'],mt['aisle'])

In [12]:
cross.head(10)

aisle,air fresheners candles,asian foods,baby accessories,baby bath body care,baby food formula,bakery desserts,baking ingredients,baking supplies decor,beauty,beers coolers,...,spreads,tea,tofu meat alternatives,tortillas flat bread,trail mix snack mix,trash bags liners,vitamins supplements,water seltzer sparkling water,white wines,yogurt
user_id,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
2,0,3,0,0,0,0,2,0,0,0,...,3,1,1,0,0,0,0,2,0,42
3,0,0,0,0,0,0,0,0,0,0,...,4,1,0,0,0,0,0,2,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
5,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,5
8,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,6,0,2,0,0,0,...,0,0,0,0,0,0,0,2,0,19
10,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2

In [13]:
pca = PCA(n_components=0.9)

In [14]:
data = pca.fit_transform(cross)

In [18]:
# data.shape
# 把样本数量减少
x = data[:500]
x.shape

(500, 27)

In [19]:
# 假设用户一共四个类别
km = KMeans(n_clusters=4)

In [20]:
km.fit(x)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=4, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [22]:
predict = km.predict(x)

In [24]:
# 显示聚类结果
plt.figure(figsize=(10,10))

In [26]:
# 建立四个颜色的列表
colored = ['orange','green','blue','purple']
colr = [colored[i] for i in predict]
plt.scatter(x[:,1],x[:,20],color = colr)

In [27]:
plt.xlabel("1")
plt.ylabel("20")

Text(0, 0.5, '20')

In [31]:
plt.show()